# ????????? ??????????
spring.application.name=project

# ????????? ??????????? ? ???? ?????? postgres 8462
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=${JDBC_USERNAME:postgres}
spring.datasource.password=${JDBC_PASSWORD:8462}

# ????????? JPA ? Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ????????? Thymeleaf
spring.thymeleaf.check-template-location=false

# ????????? JWT # ZorinDmitriSergeevich1BIB22020
jwt.secret=${SECRET_JAVA:ZorinDmitriSergeevich1BIB220208462}
jwt.expiration=3600000